import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}

// import { NavBar } from "@/ui/NavBar";
// import React from "react";
// import Image from "next/image";
// const imageOne = require("../public/microsoft_image.png");
// const imageTwo = require("../public/image.png");
// const imageThree = require("../public/microsoft_image.png");
// export default function Home() {
//   return (
//     <div className="">
//       <div className="top-0 text-center xs:py-0 py-2  w-full flex flex-wrap items-center justify-center text-white bg-[linear-gradient(90deg,#2D9D9F_0%,#2D9D9F_100%)] gap-2 xs:gap-0 text-sm">
//         <span className="text-sm py-1.5 max-sm:hidden">
//           Join our discord for early access to new features!
//         </span>
//         <span className="text-sm py-1.5 sm:hidden">
//           Join discord for early access!
//         </span>
//         <a
//           className="hover:bg-white/90 bg-white text-black rounded-full py-0.5 px-2 items-center gap-1 flex hover:cursor-pointer my-1 text-sm"
//           href="/discord"
//         >
//           Join Now
//           <svg
//             xmlns="http://www.w3.org/2000/svg"
//             width="24"
//             height="24"
//             viewBox="0 0 24 24"
//             fill="none"
//             stroke="currentColor"
//             strokeWidth="2"
//             strokeLinecap="round"
//             strokeLinejoin="round"
//             className="lucide lucide-arrow-right size-3 p-0 m-0"
//           >
//             <path d="M5 12h14"></path>
//             <path d="m12 5 7 7-7 7"></path>
//           </svg>
//         </a>
//       </div>
//       <NavBar />
//       <section className="w-full min-h-[calc(100vh-40px)] bg-gradient-to-r from-black via-[#0B5B64] to-[#001518] flex items-center justify-center">
//         <div className="absolute inset-0 object-cover object-center bg-gradient-to-r from-black via-[#0B5B64] to-[#001518] mix-blend-overlay bg-blend-darken">
//           <img
//             src="	https://smallest.ai/assets/home/nextImageExportOptimizer/hero-bg-opt-3840.WEBP"
//             alt=""
//           />
//         </div>
//         <div className="relative z-10 flex flex-col  items-center  max-w-lg justify-center gap-y-24 max-sm:gap-y-12">
//           <div className="flex flex-col items-center justify-center gap-y-4 max-sm:px-5">
//             <p className="font-space-grotesk max-sm:text-sm  font-light text-[#F2FBFA] text-center tracking-[4px]">
//               SMALLER | FASTER |BETTER
//             </p>
//             <div className="font-space-grotesk font-medium text-7xl max-sm:text-4xl text-center text-[#F2FBFA] leading-[70px] max-sm:leading-[44px]">
//               Real time AI for every human
//             </div>
//             <h3 className="text-xl max-sm:text-lg leading-[20px] max-sm:leading-[28px] text-[#F2FBFA] text-center">
//               Enabling hyper-personalised AI interactions at population scale
//             </h3>
//           </div>
//           <div>
//             <div className="flex flex-row items-center justify-center gap-y-8 border max-sm:gap-y-6">
//               <div className="">
//                 <Image
//                   src={imageOne}
//                   width={500}
//                   height={500}
//                   alt="Picture of the author"
//                 />
//               </div>
//               <div>
//                 <Image
//                   src={imageTwo}
//                   width={500}
//                   height={500}
//                   alt="Picture of the author"
//                 />
//               </div>
//               <div>
//                 <Image
//                   src={imageThree}
//                   width={500}
//                   height={500}
//                   alt="Picture of the author"
//                 />
//               </div>
//             </div>
//           </div>
//         </div>
//       </section>
//       <section>asdfadfs</section>
//     </div>
//   );
// }
